site_name: Pulsar Classifier

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: deep purple
  font:
    text: Roboto

plugins:
  - search

markdown_extensions:
  - codehilite
  - attr_list
  - admonition
  - pymdownx.superfences
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter

repo_url: https://github.com/erepr/pulsar3

nav:
  - Raw: raw.md
  - Home: index.md
  - Introduction: introduction.md
  - Workflow:
    - Application Flow: first.md
  - Data Ingestion: ingestion.md
  - Data Profiling: profile.md
  - Exploratory Data Analysis: eda.md
  - Data Preprocessing: preprocessing.md
  - Model Selection: model.md
  - Model Tuning:
    - Hyperparameter Tuning: tune.md
    - Selection Criteria: criteria.md
  - Finalize Model: final.md
  - Export Model: export.md
  - Deployment: deploy.md
  - UI Designing: ui.md
  - Monitoring: monitor.md
  - Findings & Conclusion: conclusion.md
